services:
    snowio_connector.provider.form.job_instance:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
                full_export: snowio-csv-product-export
                partial_export: snowio-csv-export
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
