parameters:
    snowio_connector.job.job_parameters.constraint_collection_provider.product.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\ProductConstraint
    snowio_connector.job.job_parameters.constraint_collection_provider.simple.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\SimpleConstraint

services:
    # Validation constraints for our JobParameters
    snowio_connector.job.job_parameters.constraint_collection_provider.full_export:
          class: '%snowio_connector.job.job_parameters.constraint_collection_provider.product.class%'
          arguments:
              - '@akeneo_pim_enrichment.job.job_parameters.constraint_collection_provider.simple_csv_export'
              - ['full_export']
          tags:
              - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    snowio_connector.job.job_parameters.constraint_collection_provider.partial_export:
          class: '%snowio_connector.job.job_parameters.constraint_collection_provider.simple.class%'
          arguments:
              - ['partial_export']
          tags:
              - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
