parameters:
    snowio_connector.step.post.class:  Snowio\Bundle\CsvConnectorBundle\Step\PostStep
    snowio_connector.step.archive.class:  Snowio\Bundle\CsvConnectorBundle\Step\ArchiveStep
    snowio_connector.step.metadata.class:  Snowio\Bundle\CsvConnectorBundle\Step\MetadataStep
    guzzlehttp.client.class: GuzzleHttp\Client
    snowio_connector.step.archive.zip.class: ZipArchive
    snowio_connector.step.media_export.class: Snowio\Bundle\CsvConnectorBundle\Step\MediaExportStep
    snowio_connector.step.check_thresholds.class: Snowio\Bundle\CsvConnectorBundle\Step\CheckThresholdsStep
    snowio_connector.media_export.export_location.class: Snowio\Bundle\CsvConnectorBundle\MediaExport\ExportLocation
    snowio_connector.media_export.logger.class: Snowio\Bundle\CsvConnectorBundle\MediaExport\Logger

services:
    guzzlehttp.client:
        class: '%guzzlehttp.client.class%'

    snowio_connector.step.archive.zip:
        class: '%snowio_connector.step.archive.zip.class%'

    snowio_connector.step.archive:
        class: '%snowio_connector.step.archive.class%'
        arguments:
            - 'archive'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@snowio_connector.step.archive.zip'
            - '@snowio_connector.media_export.logger'

    snowio_connector.media_export.export_location:
        class: '%snowio_connector.media_export.export_location.class%'
        arguments:
            - '%media_export_directory%'
            - '%media_export_host%'
            - '%media_export_user%'

    snowio_connector.media_export.logger:
        class: '%snowio_connector.media_export.logger.class%'
        arguments:
            - '%kernel.root_dir%/logs/media_export'

    snowio_connector.step.media_export:
        class: '%snowio_connector.step.media_export.class%'
        arguments:
            - 'media_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@snowio_connector.media_export.export_location'
            - '@snowio_connector.media_export.logger'
            - '%asset_storage_dir%'

    snowio_connector.step.post:
        class: '%snowio_connector.step.post.class%'
        arguments:
            - 'post'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@guzzlehttp.client'

    snowio_connector.step.metadata:
        class: '%snowio_connector.step.metadata.class%'
        arguments:
            - 'metadata'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'

    snowio_connector.step.check_threshold.products:
        class: '%snowio_connector.step.check_thresholds.class%'
        arguments:
            - 'check_thresholds'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '%minimum_products_export%'

    snowio_connector.step.check_threshold.attributes:
        class: '%snowio_connector.step.check_thresholds.class%'
        arguments:
            - 'check_thresholds'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '%minimum_attributes_export%'

    # Overwrite service definition to set step name (arg 0) and writer
    snowio_connector.step.csv_product.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_product.export'
        arguments:
            index_0: 'product'
            index_5: '@snowio_connector.writer.file.csv_product'

    snowio_connector.step.csv_product_model.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_product_model.export'
        arguments:
            index_0: 'product_model'
            index_3: '@snowio_connector.reader.database.product_model'
            index_5: '@snowio_connector.writer.file.csv_product_model'

    snowio_connector.step.csv_category.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_category.export'
        arguments:
            index_0: 'category'
            index_5: '@snowio_connector.writer.file.csv_category'

    snowio_connector.step.csv_attribute.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_attribute.export'
        arguments:
            index_0: 'attribute'
            index_5: '@snowio_connector.writer.file.csv_attribute'

    snowio_connector.step.csv_attribute_option.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_attribute_option.export'
        arguments:
            index_0: 'attribute_option'
            index_5: '@snowio_connector.writer.file.csv_attribute_option'

    snowio_connector.step.csv_family.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_family.export'
        arguments:
            index_0: 'family'
            index_5: '@snowio_connector.writer.file.csv_family'

    snowio_connector.step.csv_family_variant.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_family_variant.export'
        arguments:
            index_0: 'family_variant'
            index_5: '@snowio_connector.writer.file.csv_family_variant'

    snowio_connector.step.csv_attribute_group.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pim_connector.step.csv_attribute_group_export.export'
        arguments:
            index_0: 'attribute_group'
            index_5: '@snowio_connector.writer.file.csv_attribute_group'
