extensions:
    snowio-csv-product-export-edit:
        module: pim/form/common/edit-form

    snowio-csv-product-export-edit-main-image:
        module: pim/form/common/main-image
        parent: snowio-csv-product-export-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportCSV.svg

    snowio-csv-product-export-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: snowio-csv-product-export-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    snowio-csv-product-export-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: snowio-csv-product-export-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    snowio-csv-product-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: snowio-csv-product-export-edit
        position: 1000

    snowio-csv-product-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: snowio-csv-product-export-edit
        targetZone: content
        position: 100

    snowio-csv-product-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: snowio-csv-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_common.properties
            tabCode: snowio-properties

    snowio-csv-product-export-edit-global:
        module: pim/job/common/edit/properties
        parent: snowio-csv-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode: snowio-global

    snowio-csv-product-export-edit-content:
        module: pim/job/product/edit/content
        parent: snowio-csv-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 130
        config:
            tabTitle: pim_import_export.form.job_instance.tab.content.title
            tabCode: snowio-content

    snowio-csv-product-export-edit-history:
        module: pim/common/tab/history
        parent: snowio-csv-product-export-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 140
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_common.history
            tabCode: snowio-history

    snowio-csv-product-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_common.code
            readOnly: true

    snowio-csv-product-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_common.label
            readOnly: false

    snowio-csv-product-export-edit-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: snowio-csv-product-export-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_import_export.form.job_instance.tab.properties.decimal_separator.help

    snowio-csv-product-export-edit-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: snowio-csv-product-export-edit-global
        position: 140
        targetZone: properties
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.date_format.title
            tooltip: pim_import_export.form.job_instance.tab.properties.date_format.help

    snowio-csv-product-export-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 150
        targetZone: properties
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_import_export.form.job_instance.tab.properties.delimiter.help

    snowio-csv-product-export-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 160
        targetZone: properties
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_import_export.form.job_instance.tab.properties.enclosure.help

    snowio-csv-product-export-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: snowio-csv-product-export-edit-global
        position: 170
        targetZone: properties
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.with_header.title
            tooltip: pim_import_export.form.job_instance.tab.properties.with_header.help

    snowio-csv-product-export-edit-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: snowio-csv-product-export-edit-global
        position: 180
        targetZone: properties
        config:
            fieldCode: configuration.with_media
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.with_media.title
            tooltip: pim_import_export.form.job_instance.tab.properties.with_media.help

    snowio-csv-product-export-edit-properties-endpoint:
            module: pim/job/common/edit/field/text
            parent: snowio-csv-product-export-edit-global
            position: 180
            targetZone: properties
            config:
                fieldCode: configuration.endpoint
                readOnly: false
                label: snowio_connector.form.job_instance.tab.properties.endpoint.title
                tooltip: snowio_connector.form.job_instance.tab.properties.endpoint.help

    snowio-csv-product-export-edit-properties-application-id:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 190
        targetZone: properties
        config:
            fieldCode: configuration.applicationId
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.application_id.title
            tooltip: snowio_connector.form.job_instance.tab.properties.application_id.help

    snowio-csv-product-export-edit-properties-secret-key:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 200
        targetZone: properties
        config:
            fieldCode: configuration.secretKey
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.secret_key.title
            tooltip: snowio_connector.form.job_instance.tab.properties.secret_key.help

    snowio-csv-product-export-edit-properties-export-dir:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 210
        targetZone: properties
        config:
            fieldCode: configuration.exportDir
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.export_dir.title
            tooltip: snowio_connector.form.job_instance.tab.properties.export_dir.help

    snowio-csv-product-export-edit-properties-rsync-directory:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 220
        targetZone: properties
        config:
            fieldCode: configuration.rsyncDirectory
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_directory.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_directory.help

    snowio-csv-product-export-edit-properties-rsync-user:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 230
        targetZone: properties
        config:
            fieldCode: configuration.rsyncUser
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_user.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_user.help

    snowio-csv-product-export-edit-properties-rsync-host:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 240
        targetZone: properties
        config:
            fieldCode: configuration.rsyncHost
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_host.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_host.help

    snowio-csv-product-export-edit-properties-rsync-options:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-edit-global
        position: 240
        targetZone: properties
        config:
            fieldCode: configuration.rsyncOptions
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_options.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_options.help

    snowio-csv-product-export-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: snowio-csv-product-export-edit-content
        targetZone: structure-filters
        position: 100

    snowio-csv-product-export-edit-label:
        module: pim/job/common/edit/label
        parent: snowio-csv-product-export-edit
        targetZone: title
        position: 100

    snowio-csv-product-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: snowio-csv-product-export-edit
        targetZone: meta
        position: 100

    snowio-csv-product-export-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: snowio-csv-product-export-edit
        targetZone: buttons
        position: 50

    snowio-csv-product-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: snowio-csv-product-export-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.export_profile
                subTitle: pim_menu.item.export_profile
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    snowio-csv-product-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: snowio-csv-product-export-edit
        targetZone: buttons
        position: 120

    snowio-csv-product-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: snowio-csv-product-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    snowio-csv-product-export-edit-state:
        module: pim/form/common/state
        parent: snowio-csv-product-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    snowio-csv-product-export-edit-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: snowio-csv-product-export-edit-content-structure
        targetZone: filters
        position: 90

    snowio-csv-product-export-edit-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: snowio-csv-product-export-edit-content-structure
        targetZone: filters
        position: 100

    snowio-csv-product-export-edit-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: snowio-csv-product-export-edit-content-structure
        targetZone: filters
        position: 110

    snowio-csv-product-export-edit-content-data:
        module: pim/job/product/edit/content/data
        parent: snowio-csv-product-export-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    snowio-csv-product-export-edit-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: snowio-csv-product-export-edit-content-data
        config:
            types: [pim_catalog_identifier]

    snowio-csv-product-export-edit-content-data-help:
        module: pim/job/common/edit/content/data/help
        parent: snowio-csv-product-export-edit-content-data

    snowio-csv-product-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: snowio-csv-product-export-edit

    snowio-csv-product-export-edit-content-data-add-filter:
        module: pim/job/product/edit/content/data/add-select/attribute
        parent: snowio-csv-product-export-edit-content-data
        targetZone: headings
        position: 90
