extensions:
    snowio-csv-export-show:
        module: pim/form/common/edit-form

    snowio-csv-export-show-main-image:
        module: pim/form/common/main-image
        parent: snowio-csv-export-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-export-csv.svg

    snowio-csv-export-show-user-navigation:
        module: pim/menu/user-navigation
        parent: snowio-csv-export-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    snowio-csv-export-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: snowio-csv-export-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    snowio-csv-export-show-launch:
        module: pim/job/common/edit/launch
        parent: snowio-csv-export-show
        targetZone: meta
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code

    snowio-csv-export-show-label:
        module: pim/job/common/edit/label
        parent: snowio-csv-export-show
        targetZone: title
        position: 100

    snowio-csv-export-show-edit:
        module: pim/common/redirect
        parent: snowio-csv-export-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    snowio-csv-export-show-subsection:
        module: pim/form/common/subsection
        parent: snowio-csv-export-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    snowio-csv-export-show-grid:
        module: pim/job/common/grid
        parent: snowio-csv-export-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-export-executions-grid
            metadata:
                jobType: export
